# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/vivado/35T_lab3/project/.Xil/Vivado-199612-DESKTOP-T0S5AKR/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tftg256-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core
    D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips
  } {
      F:/software/xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/software/xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core
    D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips
  } {
      D:/vivado/35T_lab3/project/.Xil/Vivado-199612-DESKTOP-T0S5AKR/realtime/reset_sys_stub.v
      D:/vivado/35T_lab3/project/.Xil/Vivado-199612-DESKTOP-T0S5AKR/realtime/mmcm_stub.v
      D:/vivado/35T_lab3/project/.Xil/Vivado-199612-DESKTOP-T0S5AKR/realtime/axi_bram_ctrl_0_stub.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/new/axi_wrapper.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/src/clkdivider.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_biu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_clk_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_clkgate.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_core.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_cpu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_cpu_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_dtcm_ram.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_extend_csr.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_bjp.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_csrctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_dpath.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_lsuagu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_muldiv.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_alu_rglr.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_branchslv.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_commit.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_csr.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_decode.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_disp.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_excp.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_longpwbck.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_oitf.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_regfile.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_exu_wbck.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_ifu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_ifu_ifetch.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_ifu_ift2icb.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_ifu_litebpu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_ifu_minidec.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_irq_sync.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_itcm_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_itcm_ram.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_lsu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_lsu_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_reset_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/soc/e203_soc_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/core/e203_srams.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_clint.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_gfcm.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_hclkgen.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_hclkgen_rstsync.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_main.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_mems.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_perips.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_plic.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_pll.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_pllclkdiv.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/subsys/e203_subsys_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/i2c_master_bit_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/i2c_master_byte_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/i2c_master_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/new/lab3_ddr_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_1cyc_sram_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetReg.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetRegVec.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetRegVec_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetRegVec_129.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetRegVec_36.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_AsyncResetRegVec_67.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_DeglitchShiftRegister.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_LevelGateway.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_ResetCatchAndSync.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_ResetCatchAndSync_2.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_aon.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_aon_lclkgen_regs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_aon_porrst.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_aon_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_aon_wrapper.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_clint.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_clint_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/debug/sirv_debug_csr.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/debug/sirv_debug_module.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/debug/sirv_debug_ram.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/debug/sirv_debug_rom.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_expl_apb_slv.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_expl_axi_slv.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_flash_qspi.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_flash_qspi_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_gnrl_bufs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_gnrl_dffs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_gnrl_icbs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_gnrl_ram.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_gpio.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_gpio_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_hclkgen_regs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/fab/sirv_icb1to16_bus.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/fab/sirv_icb1to2_bus.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/fab/sirv_icb1to8_bus.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/debug/sirv_jtag_dtm.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_jtaggpioport.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/mems/sirv_mrom.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/mems/sirv_mrom_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_otp_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_plic_man.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_plic_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pmu.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pmu_core.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm16.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm16_core.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm16_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm8.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm8_core.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwm8_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_pwmgpioport.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_1cs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_1cs_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_4cs.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_4cs_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_arbiter.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_fifo.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_media.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_media_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_media_2.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_physical.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_physical_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_qspi_physical_2.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_queue.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_queue_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_repeater_6.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_rtc.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_sim_ram.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_spi_flashmap.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_spigpioport.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_spigpioport_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_spigpioport_2.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/general/sirv_sram_icb_ctrl.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_tl_repeater_5.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_tlfragmenter_qspi_1.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_tlwidthwidget_qspi.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_uart.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_uart_top.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_uartgpioport.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_uartrx.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_uarttx.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/perips/sirv_wdog.v
      D:/vivado/35T_lab3/project/project_1.srcs/sources_1/imports/rtl/system.v
    }
      rt::read_vhdl -lib xpm F:/software/xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/vivado/35T_lab3/project/.Xil/Vivado-199612-DESKTOP-T0S5AKR/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
