# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/35T/project/project_1.srcs/sources_1/ip/mmcm_1/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
